### ISSUE TITLE
Colors pushed up one channel 

### ISSUE THREAD

**Issue by Clyde-L** [dpitts/f16v3_issues#11]
When output from xlights I get color channels pushed up by one channel.  Testing from the v3 shows correct string color (RGB), but when output to the same set from xlights, color is off by one.  So select Red, Green is displayed. Select Green and Blue is displayed.  Select Blue, and it pushes all the channels/pixels up by one and displays Red.

Also when hooking up a singing character, and selecting no colors (default is always white), I see an odd smattering of whites, blues, and reds across the active pixels.  There are also pixels lit that should not be when the solid color is checked.

**Comment by dpitts** [comment]
Yep. The DMX output routine was destroying pixel buffer. Moved Serial output routine after the mainboard pixel output routine.
