### ISSUE TITLE
Enhancement:  USB stick support for FW update

### ISSUE THREAD

**Issue by Clyde-L** [dpitts/f16v3_issues#13]
So I'm sitting here in my kitchen where I have a good USB thumb drive.  I also have a micro SD card but I don't have the adapter to fit into my computer.  Question is, can the USB input be updated so when it boots, to look for the .fal firmware file?  It would offer yet another easy way to update the firmware. 

Thanks 
Clyde

**Comment by dpitts** [comment]
No. Very hard to get all USB drives to work. Microchip does not support this.

**Comment by Clyde-L** [comment]
Ok Thanks
