### ISSUE TITLE
Fix Null nodes. 

### ISSUE THREAD

**Issue by dpitts** [dpitts/f16v3_issues#16]
Note: I think the null nodes are not being added to total bytes count.

I think I may have stumbled on an issue on the F16V3 relating to Virtual Strings and null pixels.  I also have a V2 controller and if configured
identical to the V3 it works as expected. Here's what is happening.  I have four strings of 50 nodes connected together.  In the string port 
config I start configuring a port with the universe and then pixel count of 42 and then a null count of 8.  I then create 3 virtual strings
from this port and it just fine.  When I run the test from the controller the last string of the 4 only lights up 
10 nodes after the first 8 which are nulls, leaving 32 nodes unlit.  Duplicating this on the V2, it lights the entire 42 nodes after the 8 nulls, on the last string.
So 4 strings with 8 nulls equal 32 nulls and that is also the number of nodes that don't light up.

To further test I take one string out and the virtual string as well and just have 3 strings and this time the last string has 18 nodes lit after the 8 nulls.

**Comment by dpitts** [comment]
Added byte to total number of bytes.

**Comment by madsci1016** [comment]
Can confirm the bug!
