### ISSUE TITLE
Limit Pixel Output on to 1-4 or 1-12 for f4v3

### ISSUE THREAD

**Issue by dpitts** [dpitts/f16v3_issues#18]

**Comment by dpitts** [comment]
Fixed

**Comment by madsci1016** [comment]
Assuming this was the serial output used as a pixel output dialog? Does it have to be limited to one of the 4/12 on a F4V3 or do you have a free engine to make this a 13's output? Understand it would mean more GUI work, so may not be worth the squeeze
