### ISSUE TITLE
All values go undefined when adding virtual string

### ISSUE THREAD

**Issue by madsci1016** [dpitts/f16v3_issues#27]
On Chrome when I click (+) to add a virtual string all calculated values go undefined. Have to click save and click string ports again to get them to come back. 

![f4v3bug2](https://user-images.githubusercontent.com/1082294/32420277-26466d82-c24d-11e7-980e-cbe24ee0d0bf.PNG)

**Comment by madsci1016** [comment]
Fixed when adding a string, still there when removing a string.

**Comment by dpitts** [comment]
Fixed in 2.50 b007
