### ISSUE TITLE
Issue: test mode stays on after reboot and unchecking - after bootloader/firmware update

### ISSUE THREAD

**Issue by Kosm925** [dpitts/f16v3_issues#38]
After bo0tloader and firmware updating(for the first time) the test mode was checked "on" by default. 
unchecking test mode would stop lights, but restarting controller would turn the test mode back "on" once powered back up.
choosing a mode i.e., artnet, remote mode, master mode, or standalone mode - fixed it.
before choosing a mode, the default mode that was selected was blank. As soon as i picked a mode everything worked normal - test mode would stay unchecked even after powering off.

**Comment by JonB256** [comment]
seems to be completely fixed in b018

**Comment by Kosm925** [comment]
I have not been able to replicate sense the first bootleader/firmware update. This could've been because I was in test mode before updating. Maybe close if no one else can replicate.
