### ISSUE TITLE
Issue: Time is slipping

### ISSUE THREAD

**Issue by Kosm925** [dpitts/f16v3_issues#39]
I added a battery under the OLED and set time in settings. But over time the clock starts to slip behind. it looks like it falls behind realtime randomly, sometimes after being on for a few minutes and moving around the interface.

**Comment by dpitts** [comment]
I will switch the processors real time clock input to come from RTC output rather than internal clock.

**Comment by dpitts** [comment]
Switch real time clock to external RTC. Need to add calibration.
