### ISSUE TITLE
True Standalone Feature

### ISSUE THREAD

**Issue by greggvelez** [dpitts/f16v3_issues#40]
Once the Falcon is powered down and repowered, it appears the only way to use the standalone feature is to access the network interface and manually play the sequence on the sd card.  I would like to have a way to automatically start the falcon in standby mode (last sequence used?) when powered on (isn't that true standalone mode?) instead of having to activate it through the network interface after powering on.  Is this nit-picking?

Thanks - Gregg

**Comment by greggvelez** [comment]
standby = standalone

**Comment by greggvelez** [comment]
Also...wifi feature not working, so the only way to activate standalone mode is through hardwire network connection...eliminating a major benefit of the standalone feature.

**Comment by dpitts** [comment]
Create a schedyule that plays everyday that starts 12:00am to 11:59pm. We are working on the wifi pages.

**Comment by greggvelez** [comment]
Yes, I thought of that, but I'd rather power the unit down when it's not playing after dark.  or on a manual electric timer, for instance.

**Comment by dpitts** [comment]
If you create a schedule it will play when it is powered because the schedule will be set to always play. Maybe i am missing your point.

**Comment by greggvelez** [comment]
Yes, but I wouldn't normally have the falcon or any power supplies on during the daylight hours, only at night to display the lights.  So as-is now, if I power the falcon and power supplies down every day during daylight hours, when powering everything back up (which would be a daily occurrence) I'd have to access the network interface and manually start the standalone sequence.  Or to workaround that, I'd have to leave everything powered on 24/7, even though lights are only being displayed at night.  I'd prefer to power everything down during daylight hours and not have to manually start the standalone sequence daily, if that makes more sense.  I'm definitely open to alternatives, though, and to the possibility that I'm begging AND choosing. :-)

**Comment by greggvelez** [comment]
Maybe I'm missing the point.  Will the scheduler actually power the Falcon down, or just not play the sequence?  I'm assuming not play the sequence.  But I'll do some tests.

**Comment by dpitts** [comment]
The board would need to be powered down externally.

**Comment by dpitts** [comment]
If you create a schedule entry like I stated when the board powers up it will check the current time and look at all schedules to see if it should be playing. If the schedule is set to play everyday and all time of the day the schedule entry (playlist) will play on every power up. Have you tied what i stated because there should be no need to go to web interface after the schedule is created.

**Comment by greggvelez** [comment]
Ah, that makes total sense to me now.  Even if the board and power supplies are powered down then up, the scheduler controls when to play the sequence.  Got it.  Sorry you had to explain that further. 

Thanks David, these updates and your work are truly stellar!!

**Comment by greggvelez** [comment]
By the way, I like how you have the scheduler do a graceful stop when it's time instead of just stopping abruptly.  Nice.

**Comment by dpitts** [comment]
Hi

Thanks for all the help. I appreciate the testing a lot.

David

**Comment by Kosm925** [comment]
I find the standalone mode works. If you create a playlist and a schedule, set in standalone mode. The playlist will start within 20secs after reboot.
