### ISSUE TITLE
Issue: Multisync from Master FPP to Remote F16v3

### ISSUE THREAD

**Issue by Kosm925** [dpitts/f16v3_issues#41]
I cant seem to get Multisync to work between FPP to F16 without checking ALL REMOTES on the FPP master. I added both the wireless and wired F16v3's IP Addresses into the CSV MultiSync Remote IP List too.
Multisyncing works both in wireless and wired modes if ALL REMOTES is check, but it also puts alot of stress on the network and the wired address is not accessible via a browser anymore until reboot.

**Comment by dpitts** [comment]
This is issue with FPP and Falcon. The discovery protocol is not implemented. We need to add a manual way to add Falcon Remotes via textbox in the meantime. You can manually edit the multisync remote setting by editing the entry in the "settings" file in root directory of sd or USB storage. The entry will not be in the file until you click the "All Remotes. after that the setting will be "255.255.255.255" replace that with ip address list separated with commas. This is for testing only we are working to solve this in fpp.

**Comment by JonB256** [comment]
With the release of b018, I am now getting Remote mode function on the F16v3. Put the Wireless IP in the Master's CSV blank, copied the FSEQ files to the uSD card. 

I am running in "All Remotes" with 7 other FPP Remotes listening.

**Comment by Kosm925** [comment]
I agree with the release of b018, I can now use Remote mode and multisync between FPP and F16V3. No website lag on either wifi or wired interfaces either.
FPP side is acting weird though and the discovery protocol(or lack of), but as far as F16V3 i think this issue can be closed.
