### ISSUE TITLE
Always returns to Test Mode after a reboot

### ISSUE THREAD

**Issue by JonB256** [dpitts/f16v3_issues#43]
Latest rev "17" installed. Watching the OLED, the F16 reboots when I select either Player mode. Status screen shows I'm in E1.31/Artnet. 

I uncheck Test. Then go through menus "checking things." Either Player mode choice forces a reboot just by selecting it. When I return to Status, Test is checked again.

(the Reboots may have been happening before and I wasn't watching the OLED, but the Test mode check seems to be new)

**Comment by Kosm925** [comment]
sounds sorta similar to issue #38 and #44.

**Comment by JonB256** [comment]
Now have b018 installed. There is still an issue (seems to only be in E.131/Artnet mode) where accessing the Player/Playlist or Player/Scheduler menus force a controller reboot. That may be necessary, I can't tell, but the issue of going into Test Mode when that happens is gone.

So, I'm closing this Issue.  b018 is working well for me in every mode I've tested (except ZCPP - haven't tested that because I am a "manual config" type person.
