### ISSUE TITLE
b018 can't enter a subnet mask

### ISSUE THREAD

**Issue by PeteyHall** [dpitts/f16v3_issues#49]
Under Network Configuration, if I'm using Wifi a static config, I turn off DHCP for wireless and enter all of the relevant information.

when the controller reboots, the subnet mask under Wireless Connection is blacked out with diamonds and I can't connect to my wireless network.

Even if I turn on DHCP and my wireless, after confirming the settings are correct for the SSID/password, the controller still can't get on the network.

**Comment by dpitts** [comment]
At this time. The upgrade process requires a reset to factory settings as some of the flash settings space has changed.

**Comment by PeteyHall** [comment]
So you need everyone to do a manual reset to factory settings after reboot?  Just making sure as I’ll try that later.

**Comment by PeteyHall** [comment]
FYI, did the factory reset and it kept the subnet mask settings after but I still can't get on my wifi - is there a certain band or frequency the f16v3's will only support?  I've tried manually setting a static address as well as using DHCP but neither have worked.
![image](https://user-images.githubusercontent.com/44344796/47273024-c0e87480-d55b-11e8-9126-aaceef08d7c3.png)

**Comment by JonB256** [comment]
I put my Wireless as DHCP and it picked it up from my router. 
I have just left it as DHCP and it continues to get the same IP after reboot.

**Comment by PeteyHall** [comment]
Do you know what channels you're using? I have an AmplifiHD mesh network running AC only but the f16's don't want to talk over that band.  No matter what I do, I can't get them to join my wireless network.

**Comment by JonB256** [comment]
My Router is A,B,G,N  (no C) and things connect very reliably.
No experience with a Mesh network or AC only.  
Looking online at descriptions, it looks like it can also support 802.11 a/g/n/ac but I can't be sure from just that brief specification listing.

**Comment by dpitts** [comment]
Issue closed. Create a new issue for the wifi connect problem.
