### ISSUE TITLE
b018 Time display isn't showing the Month (October) as 10

### ISSUE THREAD

**Issue by JonB256** [dpitts/f16v3_issues#50]
It is storing the time and day and year, but displaying 00 instead of 10

My Schedule is working just fine since it isn't "month" dependent anyway.

**Comment by dpitts** [comment]
Using wrong mask bits when retrieving time from RTC. Could not be seem when month was single digit. Fixed and will be in b020

**Comment by PeteyHall** [comment]
I confirmed this works in b020
