### ISSUE TITLE
B019 Can't Set Static Address

### ISSUE THREAD

**Issue by PeteyHall** [dpitts/f16v3_issues#52]
When changing the network from DHCP to Static directly on the controller, once you set it to static, the up/down no longer works to let you change the IP/Mask/gateway.  You have to set the port to DHCP and login through the GUI to change the IP to static appropriately.

It appears that once you set it to static on the controller, even after a reboot, it appears that the controller still thinks it's in DHCP mode.

**Comment by dpitts** [comment]
Fixed in b020.

**Comment by PeteyHall** [comment]
I just installed b020 and this problem is resolved.
