### ISSUE TITLE
b020 Remote mode not working when wired

### ISSUE THREAD

**Issue by PeteyHall** [dpitts/f16v3_issues#56]
When placing the controller in Remote mode and Xscheduler is set to FPP Master, I'm unable to control lights attached to the controller and the controller doesn't show any jobs running.

When I try the same FSEQ in Standalone mode on Xscheduler and e1.31 mode on the controller, it works as expected.

Confirmed the sync was set to Wired under Misc. settings (I tried it both ways unsuccessfully).

**Comment by PeteyHall** [comment]
B021 fixed the issue, I can not do a remote f16ve.

**Comment by JonB256** [comment]
I know this is closed, but - currently, your FPP Master needs to use All Remotes for the F16v3 (b018 or b021) for Remote mode to work. Having the IP address in the CSV line is non-functioning.
