### ISSUE TITLE
b021 Wi-Fi issue

### ISSUE THREAD

**Issue by JerryPlak** [dpitts/f16v3_issues#58]
Currently on b021 and have the network settings for the Wi-Fi set as static IP 192.168.2.102.
It randomly revert to DHCP and with my Wi-Fi analyzer it shows up as 192.168.2.XXX   Reader_ae0edb

I do have go to the network page and do a save and restart to bring it back.

**Comment by JonB256** [comment]
Jerry, my Wireless IP (static at 192.168.0.25) has remained steady for weeks, through firmware updates and power cycles. Does your router allow you to Reserve an IP for the MAC used by the Espressif wireless module?

**Comment by JerryPlak** [comment]
Today's update 11/15/2018
after updating xLights to 2018.45 Released and restarting the F16V3 controller the Wi-Fi is staying connected runtime at this time is about two hours and continuing with the static IP.

**Comment by JerryPlak** [comment]
update
it's been runny for Uptime: 12:00:11 on wifi, Wi-Fi is staying connected will check in the morning 
will closes this  issue #58 in the morning.

**Comment by JerryPlak** [comment]
Update & closing issue #58.
the Wi-Fi has stayed connected for 24 hours plus now.

When I give thanks to the xLights and falcon group working in the background on this issue.
