### ISSUE TITLE
B021 Strings and Misc Settings is Gone

### ISSUE THREAD

**Issue by randyr505** [dpitts/f16v3_issues#61]
<img width="1058" alt="screen shot 2018-11-30 at 8 56 13 pm" src="https://user-images.githubusercontent.com/13177925/49323561-cf269a80-f4e2-11e8-85d6-e3ce7854cd9d.png">

When I had this connected via a network cable it was working fine. I can't recall if it was showing properly when it was disconnected from wifi but I certainly was connected via the wifi address and it was working.

**Comment by nmiller0113** [comment]
@randyr505 that's because you're accessing it over wireless.  The wireless menu is limited still.

**Comment by nmiller0113** [comment]
Just for the sake of cleanup, can you mark this as solved / closed?  Thanks!

**Comment by randyr505** [comment]
Closing, duplicate: https://github.com/dpitts/f16v3_issues/issues/60
