### ISSUE TITLE
End universe and End channel (only under Universe/Start Channel) aren’t calculated unless something typed in one of the boxes

### ISSUE THREAD

**Issue by dpitts** [dpitts/f16v3_issues#7]
String ports – End universe and End channel (only under Universe/Start Channel) aren’t calculated unless something typed in one of the boxes.  Absolute addresses are calculated all the time without typing anything in.

**Comment by dpitts** [comment]
Fixed v0.00 b002

**Comment by deplanche** [comment]
Not sure that this is fixed.  When changing the port mode from main only to main with expansions, the end universe and end channel are displayed as undefined until something is entered.  It may have to work this way, but figured I would ask to verify.

**Comment by dpitts** [comment]
This has been fixed now. b005 fixes this issue.
