### ISSUE TITLE
Smart A & C Interaction, F16V3 v2.55

### ISSUE THREAD

**Issue by jeffla** [dpitts/f16v3_issues#81]
I connected 3 smart receivers with 15(a), 27(b) and 30(c) pixels. I modeled the 3 strings in xLights and sent the config to the F16V3. String page looks good. 

On Smart-C, all pixels light up with the board in test mode, but only 15 light up when sending data from xLights. Smart-B performs as expected (all light up either way). 

All 12V pixels. Smart-C is terminated, A & B are not.

Also noticed the brightness settings are not independent. Example, setting Smart-C to 100% and A & B to 10% still outputs 10% on C. All set to 100% I get 100%. I can try other experiments if that will help.

**Comment by dpitts** [comment]
Hi

I just got home. Call me to discuss.

David

**Comment by jeffla** [comment]
Factory reset cleared up the 4 LEDs on each of the receivers. Manually configured the receivers via web (no zeros) and same results as above. Swapped mode on A & C - everything else the same (now terminating A since it's the last in the chain). All 30 light up! Physically change the chain (former A is now C and former C is now A, change termination & input from F16). All good. Put it all back as original. All good. Brightness problem disappeared as well. Computers! ¯\\_(ツ)_/¯
Closing.

**Comment by jeffla** [comment]
FYI, fully programmed from xLights 2019.64 and all is good.
