### ISSUE TITLE
Slave mode not working

### ISSUE THREAD

**Issue by ottoptika** [dpitts/f16v3_issues#84]
I have some moving heads, Hero Wash 340FX RGBW Zoom. They can run in slave mode, which works perfect in ie the "auto" programs of the lamps. But as soon as I plug in the master to the Falcon the slave lamps just shut off. 
Any known reasons for this, or any way to circumvent? 

Thanks

**Comment by AnthoneConard** [comment]
First off I would highly recommend doing research and understanding on DMX protocols when connecting anything DMX to a falcon controller each individual unit needs to be programmed with the specific address you do not use slave mode or master mode on the units when connecting them to a controller. 



Anthony Conard

**Comment by ottoptika** [comment]
Why not? It can make sense if I need to free some adressess or they all need to just do the same for a simple ambient show running off FPP and Falcon.

**Comment by AnthoneConard** [comment]
Then you would address them all the same DMX address. You had a issue and asked a question please don’t get upset when the answer isn’t what you want to here. I’m just trying to explain to you the correct way. 



Anthony Conard

**Comment by ottoptika** [comment]
Not mad at all. Weird of you to assume. Just trying to learn. DMX isn't a lot of logic and very few resources to learn. I thought it was a bug in the F16v3 since we've used master/slave with other controllers and software before.
Thanks for your replies :)

**Comment by AnthoneConard** [comment]
Think of DMX like this with the controllers. When not using the The falcon The first DMX unit put in master mode would sort of be like the controller you can use the built-in programs etc. when you use the DMX fixtures with a controller like falcon all the units need to be addressed with an address and the falcon controller acts as the master. But unfortunately it doesn’t understand about slave mode on the DMX fixtures. 



Anthony Conard
